import type { TCommentComment } from './types'

export const CommentComment: TCommentComment[] = [
  { name: '滑板摄影师_Li', time: '10:12', text: '这个点位不错，能再放个全景吗？' },
  { name: 'kickflip_lover', time: '10:18', text: '板面宽度选得刚好，稳定。' },
  { name: 'old_school_98', time: '10:22', text: '这条路我也常刷，地面很丝滑。' },
  { name: '宁波滑板阿伟', time: '10:28', text: '兄弟你这ollie高度可以啊，练了多久？' },
  { name: 'Skate_Lisa', time: '10:35', text: '喜欢你这个配色，板面哪买的？' },
  { name: 'heel_flip_pro', time: '10:41', text: '重心控制得不错，落地再稳点就更好了。' },
  { name: '滑板萌新小明', time: '10:47', text: '刚入坑，看到大佬好羡慕！' },
  { name: 'StreetShredder', time: '10:53', text: '这个公园我上周也去了，晚上灯光挺好。' },
  { name: '轴承清洁大师', time: '10:58', text: '轮子声音听着挺顺滑，用的什么轴承？' },
  { name: '独立桥铁粉', time: '11:05', text: '看你后脚发力很干脆，是不是用的独立桥？' },
  { name: '长板女孩小月', time: '11:12', text: '虽然我玩长板，但看你做动作好帅！' },
  { name: '滑板店阿Ken', time: '11:18', text: '这双鞋是Dunk SB吧？耐磨性怎么样？' },
  { name: 'ollie_苦手', time: '11:25', text: '大佬能不能出个ollie教学，我练一个月还跳不起来。' },
  { name: '周末刷街党', time: '11:31', text: '周末约一波？我也想练练这个动作。' },
  { name: '护具很重要', time: '11:38', text: '动作很帅，但记得戴护具啊！' },
  { name: '滑板圈老王', time: '11:44', text: '你这个视频发抖音了吗？我去给你点赞。' },
  { name: '脚踝终结者', time: '11:50', text: '这动作我练了三个月才成，你进步真快。' },
  { name: 'Vans_收藏家', time: '11:56', text: '同款鞋！磨破了三双了还是最爱这双。' },
  { name: 'Bones_轴承粉', time: '12:03', text: '看你滑得这么稳，轴承该保养了吧？' },
  { name: '滑板妈妈', time: '12:10', text: '我儿子也在学滑板，看了你的视频说想认识你。' },
  { name: '夜滑爱好者', time: '12:16', text: '晚上这里人多吗？想找个地方夜滑。' },
  { name: 'tre_flip_练习中', time: '12:22', text: '你这个pop好高，怎么练的？求指教。' },
  { name: '滑板摄影师_Li', time: '12:28', text: '上次拍你的素材我剪好了，发你邮箱了。' },
  { name: '新手村村长', time: '12:35', text: '收藏了，以后当参考。' },
  { name: '滑板社社长', time: '12:41', text: '加个微信，我们社团想请你来做分享。' },
]
