export type FriendMessage = {
  id: number
  from: 'me' | 'friend'
  text: string
  time: string
}

export type FriendChat = {
  id: number
  name: string
  status: string
  avatarId: number
  messages: FriendMessage[]
}

export const friendChats: FriendChat[] = [
  {
    id: 1,
    name: '李华',
    status: '在线',
    avatarId: 11,
    messages: [
      { id: 1, from: 'friend', text: '今晚想去刷街吗？', time: '19:10' },
      { id: 2, from: 'me', text: '可以，几点集合？', time: '19:12' },
      { id: 3, from: 'friend', text: '八点半老地方，带头灯。', time: '19:13' },
      { id: 4, from: 'me', text: 'OK，到！', time: '19:14' },
      { id: 5, from: 'friend', text: '我刚换了一套新轮子，今晚试试手感。', time: '19:18' },
      { id: 6, from: 'me', text: '什么硬度？我最近也在看轮子。', time: '19:20' },
      { id: 7, from: 'friend', text: '92A，刷街够用，做动作也不滑。', time: '19:21' },
      { id: 8, from: 'me', text: '那不错，我到时候踩两脚试试。', time: '19:23' },
      { id: 9, from: 'friend', text: '没问题，对了，小胖也去。', time: '19:25' },
      { id: 10, from: 'me', text: '那今晚人齐了，好久没一起滑了。', time: '19:27' },
      { id: 11, from: 'friend', text: '你最近练啥动作呢？', time: '19:30' },
      { id: 12, from: 'me', text: '在练 heel flip，还不太稳。', time: '19:32' },
      { id: 13, from: 'friend', text: '那个动作我练了好久才成，脚跟要往外勾。', time: '19:34' },
      { id: 14, from: 'me', text: '对，我老是勾不够，板子翻不完。', time: '19:36' },
      { id: 15, from: 'friend', text: '试试重心再往后压一点，前脚别太用力。', time: '19:38' },
      { id: 16, from: 'me', text: '行，今晚你帮我看看动作。', time: '19:40' },
      { id: 17, from: 'friend', text: '没问题，我顺便录个视频。', time: '19:42' },
      { id: 18, from: 'me', text: '你桥调了没？上次你说太松了。', time: '19:45' },
      { id: 19, from: 'friend', text: '调紧了一点点，现在稳多了。', time: '19:47' },
      { id: 20, from: 'me', text: '我最近也想调一下，感觉转弯不太顺。', time: '19:49' },
      { id: 21, from: 'friend', text: '你用的什么桥？', time: '19:51' },
      { id: 22, from: 'me', text: 'Thunder，用了快一年了。', time: '19:53' },
      { id: 23, from: 'friend', text: 'Thunder 挺耐用的，我朋友也在用。', time: '19:55' },
      { id: 24, from: 'me', text: '你今晚带工具吗？帮我调一下。', time: '19:57' },
      { id: 25, from: 'friend', text: '带了的，T字扳手一直在包里。', time: '19:59' },
      { id: 26, from: 'me', text: '好嘞，那八点半见。', time: '20:01' },
      { id: 27, from: 'friend', text: '我到了，你在哪？', time: '20:28' },
      { id: 28, from: 'me', text: '马上，路上堵车了，五分钟。', time: '20:29' },
      { id: 29, from: 'friend', text: '好，我先滑两圈热热身。', time: '20:30' },
      { id: 30, from: 'me', text: '到了！看到你了。', time: '20:34' },
      { id: 31, from: 'friend', text: '来吧，先试试你的 heel flip。', time: '20:35' },
      { id: 32, from: 'me', text: '好，你看我动作哪里有问题。', time: '20:36' },
      { id: 33, from: 'friend', text: '你这下蹲太深了，起来的时候节奏断了。', time: '20:38' },
      { id: 34, from: 'me', text: '好像真是，我再试一次。', time: '20:39' },
      { id: 35, from: 'friend', text: '这次好多了！脚跟勾得不错。', time: '20:41' },
      { id: 36, from: 'me', text: '终于成了！感谢指点。', time: '20:42' },
      { id: 37, from: 'friend', text: '小胖也来了，走，一起滑。', time: '20:44' },
      { id: 38, from: 'me', text: '走！今晚刷个爽。', time: '20:45' },
    ],
  },
  // 好友2：甬漂的滑手
  {
    id: 2,
    name: '甬漂的滑手',
    status: '忙碌',
    avatarId: 24,
    messages: [
      { id: 1, from: 'friend', text: '你那块板面宽度多少？', time: '昨天 21:05' },
      { id: 2, from: 'me', text: '8.25，刷街挺稳的。', time: '昨天 21:06' },
      { id: 3, from: 'friend', text: '想试试宽一点的，回头借我踩踩。', time: '昨天 21:07' },
      { id: 4, from: 'me', text: '没问题，周末带给你。', time: '昨天 21:09' },
      { id: 5, from: 'friend', text: '你最近还在练尖翻吗？', time: '昨天 21:12' },
      { id: 6, from: 'me', text: '在练，成功率还不高，十次能成两三次吧。', time: '昨天 21:14' },
      { id: 7, from: 'friend', text: '我最近在练背身翻板，摔了好几次。', time: '昨天 21:16' },
      { id: 8, from: 'me', text: '那个更难，重心要完全压后脚。', time: '昨天 21:18' },
      { id: 9, from: 'friend', text: '对，我每次都是前脚落不稳。', time: '昨天 21:19' },
      { id: 10, from: 'me', text: '下次一起练，互相录视频分析一下。', time: '昨天 21:22' },
      { id: 11, from: 'friend', text: '你用的什么轴承？', time: '昨天 21:25' },
      { id: 12, from: 'me', text: 'Bones Reds，性价比还行。', time: '昨天 21:26' },
      { id: 13, from: 'friend', text: '我也想换一套，现在这个滑起来有点涩。', time: '昨天 21:28' },
      { id: 14, from: 'me', text: 'Bones 的挺顺滑，可以试试。', time: '昨天 21:30' },
      { id: 15, from: 'friend', text: '你最近有去鄞州公园滑吗？', time: '昨天 21:33' },
      { id: 16, from: 'me', text: '上周去过一次，地面挺平的。', time: '昨天 21:35' },
      { id: 17, from: 'friend', text: '那边晚上人多吗？', time: '昨天 21:36' },
      { id: 18, from: 'me', text: '周末人多，平时还好。', time: '昨天 21:38' },
      { id: 19, from: 'friend', text: '那下次约那边吧，离我也近。', time: '昨天 21:40' },
      { id: 20, from: 'me', text: '行，周日下午？', time: '昨天 21:42' },
      { id: 21, from: 'friend', text: '可以，我两点到。', time: '昨天 21:43' },
      { id: 22, from: 'me', text: 'ok，到时候微信联系。', time: '昨天 21:45' },
      {
        id: 23,
        from: 'friend',
        text: '对了，你认识换砂纸的店吗？我那个快磨平了。',
        time: '昨天 21:48',
      },
      { id: 24, from: 'me', text: '我都是自己换的，不难。', time: '昨天 21:50' },
      { id: 25, from: 'friend', text: '那你下次帮我换一下，请你喝奶茶。', time: '昨天 21:52' },
      { id: 26, from: 'me', text: '没问题，小事。', time: '昨天 21:53' },
    ],
  },

  // 好友3：阿强
  {
    id: 3,
    name: '阿强',
    status: '离线',
    avatarId: 37,
    messages: [
      { id: 1, from: 'friend', text: '你看了那个kickflip教学吗？', time: '周二 18:40' },
      { id: 2, from: 'me', text: '看了，关键是前脚要往外拨。', time: '周二 18:42' },
      { id: 3, from: 'friend', text: '我老是踢不起来，太难了。', time: '周二 18:45' },
      { id: 4, from: 'me', text: '先练ollie，稳定了再练。', time: '周二 18:47' },
      { id: 5, from: 'friend', text: '我ollie现在能过两立了，够不够？', time: '周二 18:50' },
      { id: 6, from: 'me', text: '那够了，你踢的时候脚踝要放松一点。', time: '周二 18:52' },
      { id: 7, from: 'friend', text: '行，我周末再试试。对了，你桥多高？', time: '周二 18:55' },
      { id: 8, from: 'me', text: '中桥，52mm，刷街做动作都还行。', time: '周二 18:57' },
      { id: 9, from: 'friend', text: '我准备换一对独立桥，听说反馈很好。', time: '周二 19:00' },
      { id: 10, from: 'me', text: '独立桥确实稳，就是有点重。', time: '周二 19:03' },
      { id: 11, from: 'friend', text: '你那有独立桥吗？我想先试试手感。', time: '周二 19:06' },
      { id: 12, from: 'me', text: '我用的就是独立，周末出来滑可以试试。', time: '周二 19:08' },
      { id: 13, from: 'friend', text: '太好了，周六有空吗？', time: '周二 19:10' },
      { id: 14, from: 'me', text: '周六下午应该可以。', time: '周二 19:12' },
      { id: 15, from: 'friend', text: '那周六见，顺便帮我看看ollie动作。', time: '周二 19:14' },
      { id: 16, from: 'me', text: '没问题，你最近练的怎么样了？', time: '周二 19:16' },
      { id: 17, from: 'friend', text: '感觉原地跳还行，滑行就不稳。', time: '周二 19:18' },
      { id: 18, from: 'me', text: '滑行ollie重心要更往前压一点。', time: '周二 19:20' },
      { id: 19, from: 'friend', text: '我试试，你当初练了多久？', time: '周二 19:22' },
      { id: 20, from: 'me', text: '滑行ollie大概练了一周才稳。', time: '周二 19:24' },
      { id: 21, from: 'friend', text: '那我再练练，不着急了。', time: '周二 19:26' },
      { id: 22, from: 'me', text: '对，滑板就是慢慢来。', time: '周二 19:28' },
      { id: 23, from: 'friend', text: '你最近有看比赛吗？', time: '周二 19:30' },
      { id: 24, from: 'me', text: '看了SLS的集锦，太帅了。', time: '周二 19:32' },
      { id: 25, from: 'friend', text: '那些pro的翻板简直像在变魔术。', time: '周二 19:34' },
      { id: 26, from: 'me', text: '慢慢练，我们也能成的。', time: '周二 19:36' },
    ],
  },

  // 好友4：约拍的妹子
  {
    id: 4,
    name: '约拍的妹子',
    status: '在线',
    avatarId: 58,
    messages: [
      { id: 1, from: 'friend', text: '这周末要不要拍点素材？', time: '今天 10:02' },
      { id: 2, from: 'me', text: '可以，我下午有空。', time: '今天 10:05' },
      { id: 3, from: 'friend', text: '那我们两点半公园见。', time: '今天 10:07' },
      { id: 4, from: 'me', text: '行，我带相机。', time: '今天 10:08' },
      { id: 5, from: 'friend', text: '你带鱼眼还是长焦？', time: '今天 10:10' },
      { id: 6, from: 'me', text: '都带上吧，鱼眼拍动作，长焦拍环境。', time: '今天 10:12' },
      { id: 7, from: 'friend', text: '好，我穿那件新卫衣，颜色亮一点。', time: '今天 10:14' },
      { id: 8, from: 'me', text: '可以，我穿黑色，不会抢镜。', time: '今天 10:15' },
      { id: 9, from: 'friend', text: '哈哈，你一直都挺会配合的。', time: '今天 10:17' },
      { id: 10, from: 'me', text: '毕竟专业工具人。', time: '今天 10:18' },
      { id: 11, from: 'friend', text: '你最近有练什么新动作吗？', time: '今天 10:20' },
      { id: 12, from: 'me', text: '在练big spin，还不太稳。', time: '今天 10:22' },
      { id: 13, from: 'friend', text: '那个动作拍出来很好看！', time: '今天 10:23' },
      { id: 14, from: 'me', text: '等我练成了第一个给你拍。', time: '今天 10:25' },
      {
        id: 15,
        from: 'friend',
        text: '一言为定！对了，你上次那个视频我剪完了。',
        time: '今天 10:27',
      },
      { id: 16, from: 'me', text: '发我看看，剪得怎么样？', time: '今天 10:28' },
      { id: 17, from: 'friend', text: '配了个电子乐，节奏卡的还行。', time: '今天 10:30' },
      { id: 18, from: 'me', text: '看完了，剪得真好！发抖音了吗？', time: '今天 10:35' },
      { id: 19, from: 'friend', text: '还没，等你同意再发。', time: '今天 10:36' },
      { id: 20, from: 'me', text: '发吧，记得@我。', time: '今天 10:37' },
      { id: 21, from: 'friend', text: '好，周末再拍点新的。', time: '今天 10:38' },
      { id: 22, from: 'me', text: '你最近拍照技术进步很大。', time: '今天 10:40' },
      { id: 23, from: 'friend', text: '谢谢，多亏你当模特练手。', time: '今天 10:41' },
      { id: 24, from: 'me', text: '哈哈，互相成就。', time: '今天 10:42' },
      { id: 25, from: 'friend', text: '那周末见，我先去修图了。', time: '今天 10:44' },
      { id: 26, from: 'me', text: 'ok，周末见！', time: '今天 10:45' },
    ],
  },

  // 好友5：板店老板阿Ken
  {
    id: 5,
    name: '板店老板阿Ken',
    status: '在线',
    avatarId: 42,
    messages: [
      { id: 1, from: 'friend', text: '兄弟，新款轴承到了，要不要来看看？', time: '昨天 14:23' },
      { id: 2, from: 'me', text: '什么牌子？价格怎么样？', time: '昨天 14:25' },
      { id: 3, from: 'friend', text: 'Bones Swiss，限量款，给你留了一套。', time: '昨天 14:26' },
      { id: 4, from: 'me', text: '这个有点贵啊，我先攒攒钱。', time: '昨天 14:28' },
      {
        id: 5,
        from: 'friend',
        text: '行，我先帮你留着。对了，下周六店里办比赛，你来吗？',
        time: '昨天 14:30',
      },
      { id: 6, from: 'me', text: '什么比赛？奖品有啥？', time: '昨天 14:32' },
      { id: 7, from: 'friend', text: 'best trick，冠军送一套轮子加板面。', time: '昨天 14:33' },
      { id: 8, from: 'me', text: '那我得练练大招了，报名费多少？', time: '昨天 14:35' },
      { id: 9, from: 'friend', text: '50块，含饮料和纪念贴纸。', time: '昨天 14:36' },
      { id: 10, from: 'me', text: '行，帮我报一个。', time: '昨天 14:38' },
      { id: 11, from: 'friend', text: '好的，已经记上了。你最近练啥动作？', time: '昨天 14:40' },
      { id: 12, from: 'me', text: '在练big spin和tre flip。', time: '昨天 14:42' },
      { id: 13, from: 'friend', text: 'tre flip比赛很加分，好好练。', time: '昨天 14:44' },
      { id: 14, from: 'me', text: '嗯，争取比赛拿个名次。', time: '昨天 14:46' },
      {
        id: 15,
        from: 'friend',
        text: '你这周六有空吗？来店里帮我试一下新板面。',
        time: '昨天 14:48',
      },
      { id: 16, from: 'me', text: '可以，几点？', time: '昨天 14:50' },
      { id: 17, from: 'friend', text: '下午三点，新到的货想听听反馈。', time: '昨天 14:52' },
      { id: 18, from: 'me', text: '没问题，我带板过去。', time: '昨天 14:54' },
      { id: 19, from: 'friend', text: '对了，你那个朋友阿强是不是想换桥？', time: '昨天 14:56' },
      { id: 20, from: 'me', text: '对，他想试试独立桥。', time: '昨天 14:58' },
      { id: 21, from: 'friend', text: '我店里刚到一批独立，让他来看看。', time: '昨天 15:00' },
      { id: 22, from: 'me', text: '行，我跟他说。', time: '昨天 15:02' },
      { id: 23, from: 'friend', text: '你那个滑板群最近有活动吗？', time: '昨天 15:05' },
      { id: 24, from: 'me', text: '周末大家想去鄞州公园滑。', time: '昨天 15:07' },
      { id: 25, from: 'friend', text: '我赞助几个贴纸，帮我宣传一下店。', time: '昨天 15:09' },
      { id: 26, from: 'me', text: '好，谢谢老板！', time: '昨天 15:11' },
    ],
  },

  // 好友6：小胖
  {
    id: 6,
    name: '小胖',
    status: '离开',
    avatarId: 19,
    messages: [
      { id: 1, from: 'friend', text: '我最近胖了十斤，ollie都跳不起来了。', time: '周三 16:12' },
      { id: 2, from: 'me', text: '哈哈，你天天喝奶茶能不胖吗？', time: '周三 16:14' },
      { id: 3, from: 'friend', text: '戒不掉啊，滑完就想喝冰的。', time: '周三 16:15' },
      { id: 4, from: 'me', text: '喝无糖的，或者带电解质的水。', time: '周三 16:17' },
      { id: 5, from: 'friend', text: '难受，你今天去滑吗？', time: '周三 16:18' },
      { id: 6, from: 'me', text: '去，六点左右到广场。', time: '周三 16:19' },
      { id: 7, from: 'friend', text: '我也去，顺便减减肥。', time: '周三 16:20' },
      { id: 8, from: 'me', text: '行，带上护具，你最近总摔。', time: '周三 16:22' },
      { id: 9, from: 'friend', text: '知道了知道了，晚上见。', time: '周三 16:23' },
      { id: 10, from: 'me', text: '晚上见，别迟到。', time: '周三 16:24' },
      { id: 11, from: 'friend', text: '我到了，你在哪？', time: '周三 18:05' },
      { id: 12, from: 'me', text: '马上，买水呢。', time: '周三 18:06' },
      { id: 13, from: 'friend', text: '帮我带一瓶，冰的。', time: '周三 18:07' },
      { id: 14, from: 'me', text: '你不是要减肥吗？', time: '周三 18:08' },
      { id: 15, from: 'friend', text: '冰水没事的，又不是奶茶。', time: '周三 18:09' },
      { id: 16, from: 'me', text: '服了你了，给你带。', time: '周三 18:10' },
      { id: 17, from: 'friend', text: '谢谢兄弟！今天练啥？', time: '周三 18:12' },
      { id: 18, from: 'me', text: '我练big spin，你练ollie。', time: '周三 18:13' },
      { id: 19, from: 'friend', text: '行，你帮我看看动作。', time: '周三 18:14' },
      { id: 20, from: 'me', text: '没问题，你先热身。', time: '周三 18:15' },
      { id: 21, from: 'friend', text: '我热身完了，开始吧。', time: '周三 18:20' },
    ],
  },

  {
    id: 7,
    name: '摄影师阿杰',
    status: '离线',
    avatarId: 63,
    messages: [
      { id: 1, from: 'friend', text: '上次拍的素材我剪好了，你要不要看看？', time: '周一 20:05' },
      { id: 2, from: 'me', text: '发我看看，剪得怎么样？', time: '周一 20:07' },
      { id: 3, from: 'friend', text: '加了慢动作和转场，配了个后摇的bgm。', time: '周一 20:09' },
      { id: 4, from: 'me', text: '看完了，拍得真不错，尤其是那个大乱的角度。', time: '周一 20:15' },
      { id: 5, from: 'friend', text: '那个角度我蹲了好久才抓到。', time: '周一 20:16' },
      { id: 6, from: 'me', text: '辛苦你了，下次请你喝东西。', time: '周一 20:18' },
      {
        id: 7,
        from: 'friend',
        text: '客气啥，对了，你认识其他滑手吗？我想多拍点素材。',
        time: '周一 20:20',
      },
      { id: 8, from: 'me', text: '认识好几个，周末我约他们出来。', time: '周一 20:22' },
      { id: 9, from: 'friend', text: '太好了，到时候多拍点。', time: '周一 20:23' },
      { id: 10, from: 'me', text: '没问题，我拉个群。', time: '周一 20:25' },
    ],
  },
  {
    id: 8,
    name: '老陈（鞋贩子）',
    status: '在线',
    avatarId: 85,
    messages: [
      { id: 1, from: 'friend', text: '兄弟，新到的Dunk SB，你要不要看看？', time: '今天 09:15' },
      { id: 2, from: 'me', text: '什么配色？价格别太离谱。', time: '今天 09:17' },
      { id: 3, from: 'friend', text: '黑紫配色的，滑板款，耐磨底。', time: '今天 09:18' },
      { id: 4, from: 'me', text: '多少？我鞋快磨穿了正想换。', time: '今天 09:20' },
      { id: 5, from: 'friend', text: '给你700，别人我都卖800。', time: '今天 09:21' },
      { id: 6, from: 'me', text: '有点贵啊，能便宜点不？', time: '今天 09:22' },
      { id: 7, from: 'friend', text: '650最低了，真没赚你钱。', time: '今天 09:23' },
      { id: 8, from: 'me', text: '行吧，帮我留一双42码的。', time: '今天 09:25' },
      { id: 9, from: 'friend', text: '好，晚上来店里拿。', time: '今天 09:26' },
      { id: 10, from: 'me', text: 'OK，晚上见。', time: '今天 09:27' },
    ],
  },
]
